version: '3.4'

services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
    ports:
      - 5148:5148
  webui:
    image: webui
    build:
      context: Web.UI
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production,
    ports:
      - 8080:8080
